# Generated by Django 2.0.6 on 2018-07-30 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180729_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 7, 52, 21, 152198, tzinfo=utc)),
        ),
    ]
